### ISSUE TITLE
"Unknown method" when using eclipselink-static-weave with Lazy-Loading

### ISSUE THREAD

**Issue by oberien** [my2iu/Jinq#36] opened 2016-08-26 14:46 UTC
I use the [eclipselink-static-weave-plugin](https://github.com/empulse-gmbh/eclipselink-static-weave-plugin) during compile time for my entities. For relations between classes I use the annotations `OneToOne`,`OneToMany` and `ManyToOne`. If I use eager loading, everything will work as expected and queries execute normally. Using `FetchType.LAZY` on `OneToMany` queries also works as expected. But using lazy loading together with `OneToOne` or `ManyToOne` relational annotations, then using the field's getter-methods inside queries, I get the following exception: `org.jinq.rebased.org.objectweb.asm.tree.analysis.AnalyzerException: Unknown method Sale:getCustomer()LCustomer; encountered`.

These are my entities:

``` java
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Customer {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    private String name;
    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID")
    private List<Sale> sales;
}
```

``` java
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Sale {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    private String name;
    @ManyToOne(fetch = FetchType.LAZY)
    private Customer customer;
}
```

The following code (joining `OneToMany`) works as expected:

``` java
streams.streamAll(em, Customer.class)
        .join(c -> JinqStream.from(c.getSales()))
        .forEach(System.out::println);
```

The following one, working with `ManyToOne`, produces the issue:

``` java
streams.streamAll(em, Sale.class)
        .joinFetch(s -> JinqStream.of(s.getCustomer()))
        .forEach(System.out::println);
```

It results in

``` java
java.lang.reflect.InvocationTargetException
Caused by: java.lang.IllegalArgumentException: Could not analyze lambda code
Caused by: org.jinq.rebased.org.objectweb.asm.tree.analysis.AnalyzerException: Unknown method Sale:getCustomer()LCustomer; encountered
```

Interestingly, in the decompiled class files, the method `getCustomer` does exist:

``` java
public Customer getCustomer() {
    return this._persistence_get_customer();
}
```

**Comment by my2iu** [comment] 2016-08-26 16:00
Jinq doesn't find its getter methods by running through the classes and parsing annotations. It relies on JPA's Criteria API Metamodel to get that information:

https://github.com/my2iu/Jinq/blob/master/jinq-jpa/main/org/jinq/jpa/transform/MetamodelUtil.java#L262

So basically, Jinq relies on EclipseLink to tell it what all the 1:1 and N:1 methods are on each class. I suspect that EclipseLink is populating its metamodel incorrectly/differently after static weaving, so it would be something that would need to be fixed in EclipseLink (or you would need to manually register the fields yourself using `registerAssociationAttribute`). I don't really have time to figure out how the static weaving works. If you can supply me a small EclipseLink project that uses static weaving, I can verify whether or not that is actually the case. If it is the case though, you would have to bug the EclipseLink people yourself to get it fixed.

**Comment by oberien** [comment] 2016-10-17 08:35
Sorry for the very late response, hadn't access to the PC with the sscce until now. [Here is the code reproducing this error](https://github.com/oberien/jinq-static-weave-sscce). Just run `mvn install exec:java`.

**Comment by my2iu** [comment] 2016-10-30 22:03
Sorry. I'm a little backlogged with other stuff right now, so it might be as long as another couple of weeks before I can take a look at this.

**Comment by my2iu** [comment] 2016-11-21 21:24
It does look like the static weaver is putting incorrect information in the Criteria API's metamodel (which is where Jinq gets its JPA information from).

Without static weaving, the metamodel says that the DeclaredSingularAttributes of Sale are

```name, id, customer```

But after static weaving, the metamodel says that the DeclaredSingularAttributes of Sale are

```name, id, _persistence_get_customer_vh```

The static weaver must be renaming things or something.

**Comment by my2iu** [comment] 2016-11-21 21:38
So I'm not sure if it's the weaver that gets confused or EclipseLink. After weaving, the `Sale` class ends up with lots of new methods:

```
protected org.eclipse.persistence.indirection.WeavedAttributeValueHolderInterface _persistence_customer_vh;

public org.jinq.sscce.jpa.entities.Customer getCustomer();
protected void _persistence_initialize_customer_vh();
public org.eclipse.persistence.indirection.WeavedAttributeValueHolderInterface _persistence_get_customer_vh();
public org.jinq.sscce.jpa.entities.Customer _persistence_get_customer();
```

So maybe EclipseLink itself is getting confused about what it is the proper name of the field since things have been renamed in the weaved version. It's still possible to manually register the field, and then things work ok though.

```
streams.registerAssociationAttribute(Sale.class.getMethod("getCustomer"), "customer", false);
```

**Comment by my2iu** [comment] 2016-11-21 21:45
I'm not sure where is the best place to correct this. The metamodel information from the Criteria API is incorrect after weaving. Should the weaver fix it? Should EclipseLink fix it?

If none of them are willing to fix it, I could add special case code for detecting methods that start with "_persistence_" and end with "_vh" in the metamodel and interpreting them differently. But there is a workaround for this problem too (just manually register the renamed methods).

**Comment by SalehAly** [comment] 2017-01-26 12:58
Regarding this issue, 
If I have a Super Class and a Sub Class, and I register a method for field defined in the super class then invoke the method from the sub class, I still get Unknown Method.. any ideas?  
Shouldn't the method be inherited ?

**Comment by my2iu** [comment] 2017-01-26 17:36
Your issue is not related to static weaving in EclipseLink. Please create a new issue if you have a problem with inheritance.

In any case, did you properly set up your inheritance with JPA/EclipseLink/Hibernate? You can't just subclass things. You need to add JPA/EclipseLink/Hibernate annotations describing how the subclasses should be represented in the database.

**Comment by SalehAly** [comment] 2017-01-26 17:46
I am only registering methods because I am using static weaving in Eclipselink, thats why I commented here first. I think I had to elaborate a bit more.

I will open an issue and put a concrete example once I get back to work.

**Comment by my2iu** [comment] 2017-01-26 18:10
Ok. Static weaving is not a tested configuration with Jinq. It seems that the static weaving plugin leaves out important information that Jinq needs to figure out how to do its translation. You will need to manually register all the methods that you want to use or get the makers of the static weaving plugin to fix up their Criteria API Metamodel output so that it outputs the correct information even after static weaving.

**Comment by oberien** [comment] 2017-02-02 13:43
I dug a bit into the issue and found out the following: You are using [`singularAttrib.getJavaMember()` and call `javaMember.getName()` on it](https://github.com/my2iu/Jinq/blob/master/jinq-jpa/main/org/jinq/jpa/transform/MetamodelUtil.java#L263-L264). The Member returns `_persistence_get_customer_vh` as you said. Using `sigularAttrib.getName()` directly though i got the expected value `customer`.

Is there a specific reason you are using `Member::getName` instead of `SingularAttribute::getName`?

**Comment by my2iu** [comment] 2017-02-02 16:35
The metamodel documentation is always a little unclear, but I presumed that `SingularAttribute::getName()` only returns the name of the field in the database, while `Member::getName` returns the Java field or method that is mapped to the database field. They are often related, but they don't have to be.

The EclipseLink people (i.e. Oracle) have more resources available to fix this than I do. You should just file a bug with EclipseLink and get them to fix it on their end.

**Comment by oberien** [comment] 2017-02-02 17:43
I included hibernate into my test repository and [added `@Column(name = "uiae")` to a column](https://github.com/oberien/static-weave-sscce/blob/master/src/main/java/foo/bar/sscce/jpa/entities/Sale.java#L15). That means that `name` is now named `uiae` in the database. `customer`, being a `ManyToOne` mapping, has the name `customer_id` in the database.

Still both eclipselink and hibernate return the field name when calling `Attribute.getName`.

[This code example from RMT](https://github.com/flowerrrr/RMT/blob/master/rmt/src/main/java/de/flower/common/validation/unique/impl/HibernateColumnResolver.java#L27) also uses [`attr.getName()` to return the field name](https://github.com/flowerrrr/RMT/blob/master/rmt/src/main/java/de/flower/common/validation/unique/impl/HibernateColumnResolver.java#L46) of a given columnName. (While they match the column based on naming conventions the important part of the code is that they return `attr.getName()` as fieldName.)

Therefore I think it is safe to say that `Attribute.getName` actually returns the field's name and not the column name, while `Attribute.getJavaMember` may return an invalid field if eclipselink is used with static weaving.

If you agree to this solution, I'll provide a PR.

PS: I filed 5 issues to eclipselink about half a year ago and never received any response. That is why I don't think that a solution from their end would come any time soon.

**Comment by my2iu** [comment] 2017-02-02 18:07
Well, if the EclipseLink people are being unresponsive, I guess I can put in some hacky workarounds for it. I'll try to take a look at this issue and your other one over the weekend.

**Comment by my2iu** [comment] 2017-02-05 02:45
Actually, now that I'm digging into this and setting up some test cases to study the problem more deeply, I'm having trouble recreating the problem. It's entirely possible that I'm setting things up incorrectly, but my test cases keep running fine. 

Are you sure this isn't a problem with your Project Lombok stuff? Shouldn't the Project Lombok stuff be statically weaved *before* you do the EclipseLink static weaving?

**Comment by oberien** [comment] 2017-02-05 13:19
For testing reasons I [completely removed lombok](https://github.com/oberien/static-weave-sscce/commit/858ab4dc2e6634dd7d5c675ddc578a0cd4a22234) from my [test project](https://github.com/oberien/static-weave-sscce) and the issue still occurs that `Member.getName()` returns `_persistence_get_customer_vh`.

**Comment by my2iu** [comment] 2017-02-05 18:09
Well, I'll take another look. When I took your jinq-static-weave-sscce project, and added a [delombok phase](http://awhitford.github.io/lombok.maven/lombok-maven-plugin/usage.html) to Maven, it started to work fine.

**Comment by my2iu** [comment] 2017-02-06 05:46
I've spent several more hours on this, and to be honest, I have no idea what I'm doing. Stuff seems to be working, but I have no idea whether the static weaving is happening or not because things seem to look mostly the same either way. I can't really afford to spend more time on this. 

I keep trying to hook up static weaving into my Jinq test suites in a number of different ways, and things look the same whether it's on or off. You'll need to send me a Maven unit test that properly exhibits the static weaving problem with Jinq so that I can figure out how to set up my own build files to properly run the errors through Jinq's extensive set of tests so that I can figure out all the corner cases that need fixing.

**Comment by oberien** [comment] 2017-02-06 11:51
For the jinq-static-weave-sscce project [I completely removed lombok as dependency](https://github.com/oberien/jinq-static-weave-sscce/commit/23753d24704a9a00b661d2c8fc92535ebe4c3695) as well, but the issue is still existing.

I forked Jinq and integrated eclipselink static weaving into `jinq-jpa`'s tests in [this commit](https://github.com/oberien/Jinq/commit/45bf58b146acac21174b2c726a10d64dc8c9f410). I changed the ManyToOne relation between `Sale` and `Customer` to do lazy-loading, because only this triggers static-weaving to "produce invalid data".
With this commit 18 test cases produce errors because of `Could not analyze lambda code`:
```java
Tests in error: 
  testWhereN1Links(org.jinq.jpa.JinqJPAWhereTest): Could not analyze lambda code
  testWhereN1Link(org.jinq.jpa.JinqJPAWhereTest): Could not analyze lambda code
  testSelectN1Link(org.jinq.jpa.JinqJPASelectTest): Could not analyze lambda code
  testDate(org.jinq.jpa.JinqJPATypesTest): Could not analyze lambda code
  testNull(org.jinq.jpa.JinqJPATypesTest): Could not analyze lambda code
  testDateEquals(org.jinq.jpa.JinqJPATypesTest): Could not analyze lambda code
  testSqlTimestamp(org.jinq.jpa.JinqJPATypesTest): Could not analyze lambda code
  testCalendar(org.jinq.jpa.JinqJPATypesTest): Could not analyze lambda code
  testSqlDate(org.jinq.jpa.JinqJPATypesTest): Could not analyze lambda code
  testSqlTime(org.jinq.jpa.JinqJPATypesTest): Could not analyze lambda code
  testMin(org.jinq.jpa.JinqJPAAggregateTest): Could not analyze lambda code
  testGroupByLinkEntity(org.jinq.jpa.JinqJPAAggregateTest): Could not analyze lambda code
  testGroupByMixKeyAggregate(org.jinq.jpa.JinqJPAAggregateTest): Could not analyze lambda code
  testGroupByHaving(org.jinq.jpa.JinqJPAAggregateTest): Could not analyze lambda code
  testJoinFetchList(org.jinq.jpa.JinqJPATest): Could not analyze lambda code
  testJoinList(org.jinq.jpa.JinqJPATest): Could not analyze lambda code
  testOuterJoinFetch(org.jinq.jpa.JinqJPATest): Could not analyze lambda code
  testJoin11NMLink(org.jinq.jpa.JinqJPATest): Could not analyze lambda code
```

**Comment by my2iu** [comment] 2017-02-07 05:21
I'm able to reproduce the error now. Thanks for the detailed instructions. I'll try to dig deeper into it soon.

**Comment by my2iu** [comment] 2017-02-07 20:21
I think I've fixed it? I'm still a little unclear if the fix is comprehensive or not. Version 1.8.17 should hopefully roll out into Maven Central by tonight.

**Comment by oberien** [comment] 2017-02-07 20:45
Thank you very much! I'll give it a try on Thursday.

**Comment by SalehAly** [comment] 2017-02-09 09:52
Works for me, Thanks a lot for the great work, responsiveness and your awesome library

**Closed** 2017-02-09 13:04 UTC
